# Economic and social research questions using spatial data {#sec-why-econ-soc}

In their critical appraisal of spatial econometrics, @gibbons+overman:12
state that:

> In many (micro) economic fields—particularly development, education,
environment, labor, health, and public finance—empirical work is
increasingly concerned with questions about causality ... If we increase
an individual’s years of education, what happens to their wages? If we
decrease class sizes, what happens to student grades? These questions
are fundamentally of the type 'if we change x, what do we expect to
happen to y.' Just as with economics more generally, such questions are
fundamental to our understanding of spatial economics [@gibbons+overman:12,
p. 172-173].

In the years preceding their description of spatial econometrics
risking becoming *mostly pointless*, practicioners had been realising
that interpretation of model output was not as simple as had been
assumed. In aspatial models, there is no spatial spillover to consider,
and in time-series models, only past observations can influence
the present. However, in spatial autoregressive models using for
example the average of neighbours' values of the dependent variable
as an explanatory variable, the coefficient of the spatially lagged
dependent variable interacts with the coefficients of the independent
variables [@kelejianetal:06; @lesage+fischer:08; @ward+gleditsch:08;
@lesage+pace:09]. The correct interpretation of the estimated
coefficients of models using spatial data is, naturally, central to
exploring "'if we change x, what do we expect to happen to y.'" See
also @corrado+fingleton:12 for further discussion of the importance of
thinking of spatial econometric models as tools for studying causality
as understood at that time.
  \index{spatial econometrics}
  \index{spatial econometrics models! interpretation}
  \index{spatial lag}
  \index{causality}

A further, associated, bundle of strands of development in spatial
econometrics following 2010 also involved causality. @delgado+florax:15
draw on @rubin:74; @rubin:78 to highlight the risk posed to the
stable unit treatment value assumption (SUTVA) by unmodelled spatial
dependency in the data. This key assumption for causal alaysis "implies
that potential outcomes for person $i$ are unrelated to the treatment
status of other individuals" [@angristetal:96]. The assumption and the
risk of its violation when spatial data is modelled aspatially is also
discussed at that time by @koschinsky:13 and @baylis+ham:15.
  \index{causality}
  \index{causality! SUTVA}

Work by @delgado+florax:15 has been followed up by @bardakaetal:18 and
@bardakaetal:19, showing practically how a difference-in-difference (DID)
econometric design measuring the impact of change on a chosen dependent
variable. @dubeetal:14 approach spatial difference-in-difference in a
similar way, followed up in @dubeetal:17 and @dubeetal:21. @bardakaetal:18
express the two approaches:

> Spatial DID models have been proposed by Dubé et al. (2014) and
Delgado and Florax (2015); Delgado and Florax (2015) focus on violations
of SUTVA in the case of spillover eﬀects local to the treatment whereas
Dubé et al. (2014) focus on global eﬀects [@bardakaetal:18, p. 17].

@dubeetal:14 and work derived from this, such as @sunak+madlener:16
and @diaoetal:17, has been referred to directly and indirectly by an
increasing number of applied studies, including @fang:21, @jiaetal:21,
@qiu+tong:21, @liuetal:22, @chenetal:23, @gao+wang:23, @panetal:23,
@yu+jin:23 and @zengetal:23. Some refer to both spatial DID origins:
@chagasetal:16 and @qiu+tong:21, while some derive from @delgado+florax:15
alone: @hanetal:18 and @kosfeldetal:21. It is clear that the demand for
assessments of the consequences of for example infrastructure investments
on house prices or environmental measures is enormous, so it is likely
that such studies will continue to proliferate. Both @dubeetal:14
and @delgado+florax:15 presuppose that applied researchers using their
approaches are adequately trained in spatial econometrics, so that these
researchers are more than familiar with the spatial extensions to aspatial
econometric techniques. These spatial extensions are the core of our book.
  \index{difference-in-difference}
  \index{difference-in-difference! spatial}
  \index{spatial difference-in-difference|see {difference-in-difference, spatial}}

Before continuing to present the structure of this book, it is also
sensible to cover three "breaking" topics related to causality in a
spatial context. The first of the "breaking" topics extends regression
discontinuity designs, from discussion in @gibbonsetal:13 through
@calonicoetal:14 and @keele+titiunik:15 to @butts:23 and @butts:23b,
with @cattaneo+titiunik:22 as an up-to-date general review. While
neither @dubeetal:14 nor @delgado+florax:15 appear to be directly
backed by software, software packages for R, Python and Stata for
work by Sebastian Calonico, Matias D. Cattaneo and Rocío Titiunik is
[published](https://rdpackages.github.io/); ongoing work by [Kyle
Butts](https://github.com/kylebutts) is also available.
  \index{regression discontinuity design}

The second two "breaking" topics relate directly to @olsson:70, in
which he addressed the question of the extent to which prediction and
explanation could be seen as symmetric. Summarising his findings, Olsson
asserted that:

> ... an adequate explanation may lead to a successful prediction,
but ... successful prediction is not the same as successful
explanation. [@olsson:70, p. 230]

This relates directly to: "'if we change x, what do we expect to happen
to y'", which is more about explanation (and hence causality) than
prediction. Many contemporary quantitative methods utilise predictive
success to attempt to improve model fit, and having achieved predictive
success try to re-construct the meaning of the output model in order to
work back to explanation.

Secondly, three important surveys of causality in spatial data analysis have
appeared recently: @kolak+anselin:20, @gaoetal:22, and @akbarietal:23. All
of these take up spatial challenges to the stable unit treatment value
assumption, @kolak+anselin:20 with an example of the impact of changes in
minimum legal drinking age laws on mortality for US states. @gaoetal:22
point to the rapid extension of spatial statistics to other knowledge
domains including bioinformatics, in which causal inference is clearly
important. The main use cases considered by @akbarietal:23 are in spatial
cognition, including wayfinding processes and navigation systems, because
these are so much broader in impact than program evaluations. Because
@akbarietal:23 is a literature review, it does not propose methods, but
describes those available. They also comment that of the minority of
articles included in the review that reported what software was used,
the most commonly used software was R. Only 12 percent of the articles
cited code needed to reproduce their results [see also @wolf:23]. They 
comment:
  \index{causality}
  \index{causality! SUTVA}
  \index{reproducible research}

>  This low rate of accessibility to code is a big challenge that not
only limits reproducibility of the reviewed papers, but also affects the
portability and translation of approaches to other case studies in spatial
causal inference. ... In sum, in most of the reviewed research, there
are no clear procedures related to reproducibility and validation. We
can trust more the results of papers with straightforward approaches
with a sufficient level of details. [@akbarietal:23, p. 79]

The final "breaking" topic is the influence of spatial autocorrelation
on machine learning, statistical learning, and convolutional neural
networks. @kattenbornetal:22 study the impact of spatial autocorrelation
on the training of convolutional neural networks for data acquired by
drones, and find:
  \index{machine learning}
  \index{artificial intelligence}

> Our results suggest that violating spatial independence between
training and test data can severely inflate model apparent performance
(up to almost 30%) and, hence, lead to an overly optimistic evaluation
of the generalization of such models. [@kattenbornetal:22, p. 7]

This observation, that the violation of the assumption of spatial
independence between training, validation and test data sets prejudices
outcomes, has been recognised in much of spatial data science for years,
at least from @brenning:12. There is now an extensive literature both on
the split between training and test data sets, and on the use of fitted
models for prediction to areas that were un- or under-represented in the
data used to fit the model [@meyeretal:18; @valavietal:19; @meyeretal:19;
@schratzetal:19; @meyer+pebesma:21; @milaetal:22; @meyer+pebesma:22;
@linnenbrinketal:23]. These articles are accompanied by software
permitting the reproduction of their findings and the application of
suggested adaptations, replacing random permutations in machine learning
model fitting and tuning by spatially-aware procedures.
  \index{spatial autocorrelation}
  \index{cross-validation, spatial}
  \index{machine learning}

@kopczewska:22 summarises the current research position with regard to
spatial data use in machine learning in this way:
  \index{machine learning}
  \index{spatial autocorrelation}

> It is clear from many studies that unaddressed spatial autocorrelation
generates problems, such as overoptimistic fit of models, omitted
information and/or biased (suboptimal) prediction. Thus, an up-to-date
toolbox dealing with spatial autocorrelation should be used in all ML
models in order to ensure methodological appropriateness. [@kopczewska:22,
p. 732]

She does, however, provide encouraging examples of the spatially-informed
use of machine learning methods, and a concise overview of concepts
and a listing of relevant R packages in two appendices [@kopczewska:22,
pp. 735--749].
  \index{machine learning! spatial}
  \index{reproducible research}

@wagner+zeileis:19 use model-based recursive partitioning handling
the spatial dependencies by including the spatially lagged dependent
variable in a spatial econometric model to study heterogeneous
growth. @vidolietal22 approach heterogeneity through spatial regimes,
as do @piras+sarrias:23; all three articles are backed by software.
  \index{machine learning! spatial}
  \index{spatial lag}
  \index{spatial regimes}

@nikparvar+thill:21 give a broad review of machine learning methods
and applications to spatial data, including attention to spatial
autocorrelation, spatial scale and spatial heterogeneity. @credit:22
considers the intersection of random forest models - a machine learning
method aggregating the outout of many decision trees - and spatial
econometrics models. In addition to the inclusion of the spatially lagged
dependent variable [@wagner+zeileis:19], spatially lagged independent
variables were considered. @yosidaetal:22 compare a selection of
spatially-aware machine learning approaches and a nearest-neighbour
Gaussian process model for predicting apartment rents, following some of
the suggestions made by @credit:22; references to software are provided.
  \index{machine learning! spatial}
  \index{machine learning}
  \index{random forest model}

Consideration of machine learning and the application of deep
learning/neural networks overlaps in a fair number of cases, raising
similar concerns about how the probable lack of independence between
proximate observations in space will be handled. @ahmedetal:21 stress
the need for interpretability and explainability in deep learning/neural
networks (also known as artificial intelligence) as well as in machine
learning, and explore model agnostic greedy explanations of model
predictions; references to software are provided.
  \index{deep learning}
  \index{artificial intelligence}

@zhangetal:22 and @dengetal:23 also focus on interpretability of machine
learning methods for predicting crime risk; @dengetal:23 provide their
complete data set. @zhuetal:22 [minor correction @zhuetal:23] propose
spatial regression graph convolutional neural networks for modelling and
predicting multivariate spatial data, also considering what is known as
feature selection (or engineering), which is related to interpretability;
references to software are provided.
  \index{spatial regression model}
  \index{deep learning}

@lietal:23, like @credit:22, introduce the spatially lagged dependent
variable (whether a manhole in an urban drainage system overflows or
not) into a deep neural network model. @xiaoetal:23 and @wang+song:23
in two articles with overlapping authorships look more closely at
integrating adaptations of classical spatial econometrics models -
spatial autoregressive models - into deep neural network models, both
making nonparametric additions to the classical models.
  \index{spatial regression model}
  \index{deep learning}
  \index{artificial intelligence}

The literatures covering the interpretation of spatial econometric
models, causality when the data used are spatial and so challenge standard
econometric assumptions, and training/test set data splits affecting
machine learning and artificial intelligence applications, are all
burgeoning. It might be thought that the superficial mentioning of these
questions in this section should direct us to focus attention in this book
on emerging research opportunities. However, our reading of contributions
to the current literature, taken with readings of the many other articles
published since 2020 - @dubeetal:14 has been cited hundreds of times,
mostly since 2020 - suggests that many authors would benefit substantially
from a clearer grasp of the background to spatial econometric models,
and many of their internal characteristcs. Hence, based in part on this
motivation, we will now move to present the structure of this book.


