project:
  type: book

book:
  title: "Spatial Econometrics"
  subtitle: "Team project using R"
  author:
    - name: Roger Bivand
      orcid: 0000-0003-2392-6140
      email: Roger.Bivand@nhh.no
      url: https://www.nhh.no/en/employees/faculty/roger-bivand/
      affiliations:
      - name: Norwegian School of Economics
        city: Bergen
        country: Norway
  date: today
  chapters:
    - index.qmd
    - day_1.qmd
    - day_2.qmd
    - day_3.qmd
    - references.qmd

bibliography: [bib/references.bib, packages.bib, bib/book.bib]

execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    theme: cosmo
    embed-resources: true
    html-math-method: katex
    citations-hover: true
    footnotes-hover: true



