project:
  type: book
  output-dir: docs

book:
  title: "Spatial Econometrics"
  subtitle: "Team project using R"
  author:
    - name: Roger Bivand
      orcid: 0000-0003-2392-6140
      email: Roger.Bivand@nhh.no
      url: https://www.nhh.no/en/employees/faculty/roger-bivand/
      affiliations:
      - name: Norwegian School of Economics
        city: Bergen
        country: Norway
  date: today
  chapters:
    - index.qmd
    - 01_talk.qmd
    - 02_talk.qmd
    - 03_talk.qmd
    - 04_talk.qmd
    - 05_talk.qmd
    - 06_talk.qmd
    - 07_talk.qmd
    - 08_talk.qmd
    - 09_talk.qmd
    - 10_talk.qmd
    - 11_talk.qmd
    - 12_talk.qmd
    - 13_talk.qmd
    - references.qmd

bibliography: [bib/references.bib, packages.bib, bib/book.bib]

execute:
  freeze: auto  # re-render only when source changes

highlight-style: pygments

format:
  html:
    theme: cosmo
    html-math-method: katex
    minimal: true
    code-copy: true
    code-overflow: wrap

