# Course description {.unnumbered}

### Planned topics

- Introducing Spatial Econometrics
- Spatial data
- Working with spatial data
- Creating spatial weights objects
- Spatial Econometrics: Antecedents
- Economic and social research questions using spatial data
- Tests of spatial autocorrelation, model specification
- Spatial autoregressive models: conditional (CAR) and simultaneous (SAR)
- Estimation of spatial autoregressive models: methods (GMM, ML, Bayesian)
- No orthogonality between regression and autoregression coefficients
- Prediction and spatial models
- Eigenvectors and eigenvalues of graphs of relationships between cross-sectional observations

### Team projects

The teams should aim to prepare notebooks showing reasoning, code, workflow, conclusions, and should include a log of team discussions, and the conclusions should show how the team, with hindsight, might have modified the topics and workflow had more time, data, or other resources been available. 

Teams should try to limit joint team work to the 30 hours available, but team members may choose to make progress individually to tackle technical snags. The team may choose to delegate parts to team members; use of GitHub or similar to share writing of the notebook is encouraged.

- establish communication through moodle for on-demand consultations in or outside the scheduled project hours
- week 11: draft team project proposals to be decided
- week 12: feedback on progress with projects
- week 15: mid-term team project reports
- week 16: feedback on progress with projects
- week 17: feedback on progress with projects
- Monday 6 May, 15:15-18:00 presentation of team projects and wrap-up

### Online resources

- @pebesma+bivand:23 is also available at: (https://r-spatial.org/book)
- More on constructing spatial neighbour objects: (https://r-spatial.github.io/spdep/articles/nb_sf.html)
- Spatial weights as graphs: (https://r-spatial.github.io/spatialreg/articles/nb_igraph.html)
- EMOS talk 19 April 2023: (https://rsbivand.github.io/emos_talk_2304/), (https://www.youtube.com/watch?v=spYPyHxa7v8)
- UAM short courses: (https://rsbivand.github.io/UAM21_I/), (https://rsbivand.github.io/UAM21_II/)
- WhyR 2020 keynote: (https://www.youtube.com/watch?v=mEAyQ8bv1zU)
- 2020 BAN 422 Masters course Visualization: (https://rsbivand.github.io/BAN422_V20/)
- ECS530 PhD course 2019 (with recorded talks): (https://rsbivand.github.io/ECS530_h19/), (https://www.youtube.com/watch?v=KkIbg50Pa0I&list=PLXUoTpMa_9s10NVk4dBQljNOaOXAOhcE0)
- 2019 BAN 421 Masters course Data structures: (https://rsbivand.github.io/ban421_h19/)

Spatial Econometrics: Team project using R © 2024 by Roger Bivand is licensed under [CC BY-NC-ND 4.0](http://creativecommons.org/licenses/by-nc-nd/4.0/)

Spatial Econometrics: Team project using R © 2024 by Roger Bivand is licensed under Attribution-NonCommercial-NoDerivatives 4.0 International. To view a copy of this license, visit (http://creativecommons.org/licenses/by-nc-nd/4.0/)
