<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-99.9.9">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Spatial Econometrics – 2&nbsp; Spatial data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03_talk.html" rel="next">
<link href="./01_talk.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02_talk.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Spatial data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Spatial Econometrics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course description</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducing Spatial Econometrics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_talk.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Spatial data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Working with spatial data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Creating spatial weights objects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Antecedents</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Economic and social research questions using spatial data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tests of spatial autocorrelation, model specification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Spatial autoregressive models: conditional (CAR) and simultaneous (SAR)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Estimation of spatial autoregressive models: methods (ML, Bayesian, GMM)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">No orthogonality between regression and autoregression coefficients</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Prediction and spatial models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_talk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Eigenvectors and eigenvalues of graphs of relationships between cross-sectional observations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-sd-basics" id="toc-sec-sd-basics" class="nav-link active" data-scroll-target="#sec-sd-basics"><span class="header-section-number">2.1</span> Spatial data basics</a></li>
  <li><a href="#sec-sd-crs" id="toc-sec-sd-crs" class="nav-link" data-scroll-target="#sec-sd-crs"><span class="header-section-number">2.2</span> Coordinate reference systems</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-sd" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Spatial data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In section <a href="01_talk.html#sec-why-special" class="quarto-xref"><span>Section 1.1</span></a>, we showed why spatial data should be treated as “special” until it is shown that they do not require the application of specific methods to handle combinations of spatial autocorrelation, spatial scale and spatial heterogeneity. We did not there develop the concepts and tools needed for understanding and handling spatial data before analysis, or the presentation of results from spatial econometric models in spatial form. This treatment builds on <span class="citation" data-cites="pebesma+bivand:23">Pebesma and Bivand (<a href="references.html#ref-pebesma+bivand:23" role="doc-biblioref">2023</a>)</span> chapters 1–6 and the R packages used there, but will also to some extent indicate where that software usage is matched in Python and elsewhere, for example <span class="citation" data-cites="reyetal:23">Rey, Arribas-Bel, and Wolf (<a href="references.html#ref-reyetal:23" role="doc-biblioref">2023</a>)</span>; for a comparative description, see <span class="citation" data-cites="bivand:22">Bivand (<a href="references.html#ref-bivand:22" role="doc-biblioref">2022</a>)</span>. If the reader is unfamiliar with data of this kind, they may benefit from <span class="citation" data-cites="lovelaceetal:19">Lovelace, Nowosad, and Muenchow (<a href="references.html#ref-lovelaceetal:19" role="doc-biblioref">2019</a>)</span>.</p>
<section id="sec-sd-basics" class="level2" data-number="2.1">
<h2 data-number="2.1" data-anchor-id="sec-sd-basics"><span class="header-section-number">2.1</span> Spatial data basics</h2>
<p>Spatial data are observations on variables, be they categorical, ordinal or continuous. The observations are associated with a position in space, where space is often represented as (sets of) coordinate tuplets on a map; spatial data are also found in bioinformatics and medical imaging, but here we are concerned with geographical spatial data.</p>
<p>Geographical spatial data take two forms: spatial vectors and spatial rasters. Spatial vector objects are most often represented by geometries of sets of pairs of coordinates known as eastings and northings, or longitude and latitude, forming points, lines or polygons; three-dimensional spatial vectors are not often used but may be provided by data sources. Spatial raster objects are regular square or rectangular grids of cells, most like digital images. Spatial rasters are fixed to a spatial point of origin and the locations of cells can be found from the point of origin by stepping out from the origin cell and summing the distances crossing intervening calls measured by the size or resolution of the cells. Rasters have one or more bands, and may also be termed spatial data cubes, structured by two or three spatial dimensions (three if height/depth is included) and a time dimension in addition to bands containing sensor measurements.</p>
<p>While spatial raster objects include attribute data - observations on variables taken at the location of each cell, spatial vector objects do not have to do so. Observations on variables of interest are linked to geometries through a common key or identifier. The key linking the observations with the spatial vector geometries may often be a standard code published and updated by a government statistical office. Not infrequently, the data are acquired or downloaded including the key, and the geometries of the spatial objects are acquired or downloaded separately, to be merged by the observation keys afterwards. Noting the timestamp specifying the validity of geometries and keys is always sensible, as both keys and geometries change over time. We will return to the representation of time in spatial panel objects, where the geometries are invariant but variables of interest are observed over successive time periods.</p>
<p>For the present, spatial data will be taken as-is; we will return to reading and writing spatial data from and to files in Section <a href="03_talk.html#sec-sd-io" class="quarto-xref"><span>Section 3.3</span></a>. The comprehensive R archive network (CRAN) provides software packages and short summaries called task views listing packages useful for particular tasks. The Spatial task view (https://cran.r-project.org/view=Spatial) lists packages accessing or providing specific data sources of interest. Here we will use three such packages: <code>chilemapas</code> with administrative boundaries for Chile, and <code>rgugik</code> for Poland, <code>elevatr</code> for spatial raster elevation data, and <code>osmdata</code> for OpenStreetMap information. The representation of the spatial vector data is handled by the <code>sf</code> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setenv</span>(<span class="st">"PROJ_NETWORK"</span><span class="ot">=</span><span class="st">"ON"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.3.1; sf_use_s2() is TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(chilemapas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mapa_comunas <span class="sc">|&gt;</span> <span class="fu">data.frame</span>() <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">sf_column_name=</span><span class="st">"geometry"</span>) <span class="ot">-&gt;</span> mc_sf</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>mc_sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 345 features and 3 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -109.4499 ymin: -56.52511 xmax: -66.41617 ymax: -17.49778
Geodetic CRS:  SIRGAS 2000
First 10 features:
   codigo_comuna codigo_provincia codigo_region                       geometry
1          01401              014            01 MULTIPOLYGON (((-68.86081 -...
2          01403              014            01 MULTIPOLYGON (((-68.65113 -...
3          01405              014            01 MULTIPOLYGON (((-68.65113 -...
4          01402              014            01 MULTIPOLYGON (((-69.31789 -...
5          01404              014            01 MULTIPOLYGON (((-69.39615 -...
6          01107              011            01 MULTIPOLYGON (((-70.1095 -2...
7          01101              011            01 MULTIPOLYGON (((-70.09894 -...
8          02104              021            02 MULTIPOLYGON (((-68.98863 -...
9          02101              021            02 MULTIPOLYGON (((-70.60654 -...
10         02201              022            02 MULTIPOLYGON (((-67.94302 -...</code></pre>
</div>
</div>
<p>The <code>mapa_comunas</code> data object stored in the <code>chilemapas</code> package is represented as a tibble and an <code>sf</code> object. Because most model fitting objects expect data as a <code>data.frame</code> not a <code>tbl</code> also known as a tibble, we coerce to <code>data.frame</code> and re-construct the <code>sf</code> object using the <code>sf::st_as_sf</code> method for <code>data.frame</code> objects. The disparity between <code>data.frame</code> and <code>tbl</code> objects is that when a single column of a <code>data.frame</code> is selected with the <code>[</code> method, it becomes a vector by default, but the <code>[</code> method on a single column of a <code>tbl</code> object returns a <code>tbl</code> by default. The <code>geometry</code> column is an <code>sfc</code> object, a list column of <code>sfg</code> objects, where <code>sfg</code> means “Simple Feature” geometry.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(mc_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 345 features 
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -109.4499 ymin: -56.52511 xmax: -66.41617 ymax: -17.49778
Geodetic CRS:  SIRGAS 2000
First 5 geometries:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((-68.86081 -21.28512, -68.92172 ...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((-68.65113 -19.77188, -68.81182 ...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((-68.65113 -19.77188, -68.63545 ...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((-69.31789 -19.13651, -69.2717 -...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>MULTIPOLYGON (((-69.39615 -19.06125, -69.40025 ...</code></pre>
</div>
</div>
<p>The geometry column contains 345 multi-polygon objects, containing the boundaries of Chilean municipalities in 2017, clipped to the coastline. They are multi-polygons because at least some municipalities are composed of island and mainland parts. The short summary printed here also states that the geometries have a geodetic coordinate reference system (CRS), here specified as SIRGAS 2000. We return to coordinate reference systems in the next section <a href="#sec-sd-crs" class="quarto-xref"><span>Section 2.2</span></a>, but note that area calculation is conducted on the specified ellipsoid using the <code>s2</code> by default, not on the plane.</p>
<p>Let us find the area of Región del Maule, region <code>"07"</code>, of which Taule is the capital city, using the region key column in the <code>sf</code> object named <code>mc_sf</code>. First we subset the municipalities to the desired region, then union the municipalities in Región del Maule before finding the area of the region as a whole.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mc_sf <span class="sc">|&gt;</span> <span class="fu">subset</span>(<span class="at">subset=</span>codigo_region <span class="sc">==</span> <span class="st">"07"</span>) <span class="ot">-&gt;</span> maule_sf</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>maule_sf <span class="sc">|&gt;</span> <span class="fu">st_union</span>() <span class="sc">|&gt;</span> <span class="fu">st_area</span>() <span class="sc">|&gt;</span> units<span class="sc">::</span><span class="fu">set_units</span>(<span class="st">"km2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>30297.84 [km^2]</code></pre>
</div>
</div>
<p>The result agrees adequately with 30,296.1 square kilometres given by <a href="https://en.wikipedia.org/wiki/Regions_of_Chile">Wikipedia</a>, as the details of administrative boundaries and hence the computed area are compromises between detail and the size of the data object stored in the package. By default the results of length or area calculations for spherical coordinates are returned by <code>s2</code> in metres or square metres, so we convert to square kilometres.</p>
<p><code>sf</code> objects pay attention to the support of variables, whether they may be classed as constant, aggregate, or identity. Constant variables are constant across the whole area of a polygon, for example a land use category. Aggregate variables may be counts, rates based on counts, or densities of counts by polygon area. Identity variables uniquely identify the geometries. In the case of the Región del Maule data set, no definitions have so far been provided, so when we change support from polygon to point by computing the spherical centroid, a warning is given <span class="citation" data-cites="pebesma+bivand:23">(see <a href="references.html#ref-pebesma+bivand:23" role="doc-biblioref">Pebesma and Bivand 2023, 49–52</a>)</span>. <code>st_agr</code> returns the current state of the factor (categorical object) for the non-geometry variables included in the <code>sf</code> object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_agr</span>(maule_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   codigo_comuna codigo_provincia    codigo_region 
            &lt;NA&gt;             &lt;NA&gt;             &lt;NA&gt; 
Levels: constant aggregate identity</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>maule_sf <span class="sc">|&gt;</span> <span class="fu">st_centroid</span>() <span class="ot">-&gt;</span> maule_sf_pt1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: st_centroid assumes attributes are constant over geometries</code></pre>
</div>
</div>
<p>We can avoid the warning by taking the centroid of the geometries alone, of the <code>sfc</code> object rather than the <code>sf</code> object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>maule_sf <span class="sc">|&gt;</span> <span class="fu">st_geometry</span>() <span class="sc">|&gt;</span> <span class="fu">st_centroid</span>() <span class="ot">-&gt;</span> maule_sfc_pt2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Alternatively, since there are few non-geometry columns in the data set, we can assign the appropriate values to them, so that since the change of support does not change the meaning of the variables, no warning is given:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>maule_sf <span class="sc">|&gt;</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_agr</span>(<span class="fu">c</span>(<span class="at">codigo_comuna=</span><span class="st">"identity"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">codigo_provincia=</span><span class="st">"identity"</span>, </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">codigo_region=</span><span class="st">"constant"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>            ) <span class="ot">-&gt;</span> maule_sf_agr</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">st_agr</span>(maule_sf_agr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   codigo_comuna codigo_provincia    codigo_region 
        identity         identity         constant 
Levels: constant aggregate identity</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>maule_sf_agr <span class="sc">|&gt;</span> <span class="fu">st_centroid</span>() <span class="ot">-&gt;</span> maule_sf_pt3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The three remaining packages download spatial data from public sources rather than pre-packaging them for use. <code>elevatr</code> can be used to download global elevation data as a spatial raster; until version 1 of the package is released, it returns a <code>"RasterLayer"</code> as defined in the legacy <code>raster</code> package, but from 1.0 will return a <code>"SpatRaster"</code> defined in the <code>terra</code> package. Here we specify our area of interest by passing the <code>sf</code> spatial vector object for Región del Maule, and clip the output to the boundary of the region, setting negative values to missing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(elevatr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>elevatr v0.99.0 NOTE: Version 0.99.0 of 'elevatr' uses 'sf' and 'terra'.  Use 
of the 'sp', 'raster', and underlying 'rgdal' packages by 'elevatr' is being 
deprecated; however, get_elev_raster continues to return a RasterLayer.  This 
will be dropped in future versions, so please plan accordingly.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>terra 1.7.71</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>maule_sf <span class="sc">|&gt;</span>  <span class="fu">get_elev_raster</span>(<span class="at">z =</span> <span class="dv">7</span>,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a> <span class="at">clip =</span> <span class="st">"locations"</span>, <span class="at">neg_to_na =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">rast</span>() <span class="ot">-&gt;</span> maule_elev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Mosaicing &amp; Projecting</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Clipping DEM to locations</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Note: Elevation units are in meters.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>maule_elev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
dimensions  : 371, 493, 1  (nrow, ncol, nlyr)
resolution  : 0.005009617, 0.005009617  (x, y)
extent      : -72.78435, -70.3146, -36.54143, -34.68287  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs 
source(s)   : memory
name        : filee6328d7c555 
min value   :               0 
max value   :            3936 </code></pre>
</div>
</div>
<p>The raster has one layer (band), with a square (geodetic) grid with a resolution of about 0.005 degrees, 18.03 arc seconds in both dimensions, 371 rows and 493 columns.</p>
<p>Let us now access OpenStreetMap data using <code>osmdata</code> <span class="citation" data-cites="padghametal:17">(<a href="references.html#ref-padghametal:17" role="doc-biblioref">Mark Padgham et al. 2017</a>)</span>, first subsetting to the city of Talca, the capital of Región del Maule. To set up a query, we need to build an OpenStreetMap Overpass query using a bounding box of our area of interest. Since it can be difficult to know what kinds of data have been contributed, we add the <code>"names"</code> feature, pulling in everything in the rectangle defined in degrees of longitude and latitude - obviously the top and bottom of the rectangle are actually curves, because the rectangle is on the surface of an ellipsoid. Having created the query <code>talca_q</code>, we can extract the data for all features with names:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>maule_sf <span class="sc">|&gt;</span> <span class="fu">subset</span>(<span class="at">subset =</span> codigo_comuna<span class="sc">==</span><span class="st">"07101"</span>) <span class="ot">-&gt;</span> talca_sf</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(osmdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>talca_sf <span class="sc">|&gt;</span> <span class="fu">st_bbox</span>() <span class="sc">|&gt;</span> <span class="fu">opq</span>() <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">add_osm_feature</span>(<span class="at">key =</span> <span class="st">"names"</span>) <span class="ot">-&gt;</span> talca_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>talca_q <span class="sc">|&gt;</span> <span class="fu">osmdata_sf</span>() <span class="ot">-&gt;</span> talca_osm_sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>talca_osm_sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Object of class 'osmdata' with:
                 $bbox : -35.5310255,-71.723806,-35.3118342,-71.4925696
        $overpass_call : The call submitted to the overpass API
                 $meta : metadata including timestamp and version numbers
           $osm_points : 'sf' Simple Features Collection with 134548 points
            $osm_lines : 'sf' Simple Features Collection with 14580 linestrings
         $osm_polygons : 'sf' Simple Features Collection with 1090 polygons
       $osm_multilines : 'sf' Simple Features Collection with 20 multilinestrings
    $osm_multipolygons : 'sf' Simple Features Collection with 22 multipolygons</code></pre>
</div>
</div>
<p>The output object is a list of components, some of which are <code>sf</code> objects. If we take the point objects, we can attempt to subset to those said to offer take-away service, that is those for which the <code>takeaway</code> variable is not coded <code>NA</code> - missing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>talca_osm_sf<span class="sc">$</span>osm_points <span class="ot">-&gt;</span> talca_pts</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>talca_pts <span class="sc">|&gt;</span> <span class="fu">subset</span>(<span class="at">subset =</span> <span class="sc">!</span><span class="fu">is.na</span>(takeaway), </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a> <span class="at">select =</span> <span class="fu">c</span>(osm_id, name, amenity, cuisine,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  takeaway, geometry)) <span class="ot">-&gt;</span> talca_takeaways</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>talca_takeaways</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 11 features and 5 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -71.68909 ymin: -35.44643 xmax: -71.62727 ymax: -35.42225
Geodetic CRS:  WGS 84
First 10 features:
               osm_id                 name    amenity        cuisine takeaway
1237856768 1237856768              Rossini       cafe       sandwich      yes
1264154772 1264154772            Telepizza  fast_food          pizza      yes
2853291904 2853291904             La Cleta restaurant           &lt;NA&gt;      yes
2853679104 2853679104          3 Estrellas        pub       sandwich      yes
2858522001 2858522001 Cafetería Riquíssimo restaurant       regional      yes
3377351170 3377351170             Me Gustó  fast_food         burger      yes
3699062703 3699062703       Talca Sandwich  fast_food         burger      yes
3766018631 3766018631           El Chilote restaurant fish_and_chips      yes
7233542316 7233542316           McDonald's  fast_food         burger      yes
7862158443 7862158443          Papa John's  fast_food          pizza      yes
                              geometry
1237856768 POINT (-71.66275 -35.42618)
1264154772 POINT (-71.63046 -35.43272)
2853291904 POINT (-71.66563 -35.42866)
2853679104 POINT (-71.65372 -35.42822)
2858522001 POINT (-71.66378 -35.42624)
3377351170 POINT (-71.68909 -35.44643)
3699062703 POINT (-71.68062 -35.43947)
3766018631 POINT (-71.67028 -35.42225)
7233542316 POINT (-71.65486 -35.42561)
7862158443 POINT (-71.68665 -35.44302)</code></pre>
</div>
</div>
<p>There only appear to be 11 such establishments, but perhaps these are the ones whose locations grateful clients (or ambitious proprietors) have contributed to OpenStreetMap.</p>
<p>The <code>rgugik</code> package <span class="citation" data-cites="dyba+nowosad:21">(<a href="references.html#ref-dyba+nowosad:21" role="doc-biblioref">Dyba and Nowosad 2021</a>)</span> does not bundle the municipality boundaries of Poland as <code>chilemapas</code> did for Chile, but downloads them from the Polish Head Office of Geodesy and Cartography (GUGIK) online. The object returned from a query to the boundaries of the Gdańsk county administrative unit is an <code>sf</code> object with a single variable, the identification key.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rgugik)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>gd_sf <span class="ot">&lt;-</span> <span class="fu">borders_get</span>(<span class="at">county =</span> <span class="st">"Gdańsk"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>gd_sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 1 field
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 462961.1 ymin: 712372.4 xmax: 496776.7 ymax: 731607.8
Projected CRS: ETRF2000-PL / CS92
  TERYT                           geom
1  2261 MULTIPOLYGON (((465078.9 73...</code></pre>
</div>
</div>
<p>Again, we can use the <code>sf</code> object to access elevation data, here returned with about 88 metre resolution, as the input object has a projected coordinate reference system:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>gd_sf <span class="sc">|&gt;</span>  <span class="fu">get_elev_raster</span>(<span class="at">z =</span> <span class="dv">9</span>,</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a> <span class="at">clip =</span> <span class="st">"locations"</span>, <span class="at">neg_to_na =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">rast</span>() <span class="ot">-&gt;</span> gd_elev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Mosaicing &amp; Projecting</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Clipping DEM to locations</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Note: Elevation units are in meters.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>gd_elev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatRaster 
dimensions  : 216, 379, 1  (nrow, ncol, nlyr)
resolution  : 89.09542, 89.09542  (x, y)
extent      : 462973.9, 496741.1, 712362.5, 731607.1  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=tmerc +lat_0=0 +lon_0=19 +k=0.9993 +x_0=500000 +y_0=-5300000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
source(s)   : memory
name        : filee63abcb0de 
min value   :              0 
max value   :            177 </code></pre>
</div>
</div>
<p>As we just observed, <code>gd_sf</code> has a projected coordinate reference system, so needs to be transformed to a geodetic coordinate reference system before the creation of an Openpass query, here for <code>"amenity"</code> features:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>gd_sf <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="st">"OGC:CRS84"</span>) <span class="sc">|&gt;</span> <span class="fu">st_bbox</span>() <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">opq</span>() <span class="sc">|&gt;</span> <span class="fu">add_osm_feature</span>(<span class="at">key =</span> <span class="st">"amenity"</span>) <span class="ot">-&gt;</span> gd_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>gd_q <span class="sc">|&gt;</span> <span class="fu">osmdata_sf</span>() <span class="ot">-&gt;</span> gd_osm_sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>gd_osm_sf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Object of class 'osmdata' with:
                 $bbox : 54.274974489,18.429497095,54.447218154,18.9503794130001
        $overpass_call : The call submitted to the overpass API
                 $meta : metadata including timestamp and version numbers
           $osm_points : 'sf' Simple Features Collection with 64129 points
            $osm_lines : 'sf' Simple Features Collection with 30 linestrings
         $osm_polygons : 'sf' Simple Features Collection with 5946 polygons
       $osm_multilines : 'sf' Simple Features Collection with 1 multilinestrings
    $osm_multipolygons : 'sf' Simple Features Collection with 19 multipolygons</code></pre>
</div>
</div>
<p>Once again we extract the locations of registered take-away outlets, of which many more seem to have been contributed to OpenStreetMap than in the case of the bounding box surrounding the city of Talca:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>gd_osm_sf<span class="sc">$</span>osm_points <span class="ot">-&gt;</span> gd_pts</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>gd_pts <span class="sc">|&gt;</span> <span class="fu">subset</span>(<span class="at">subset =</span> <span class="sc">!</span><span class="fu">is.na</span>(takeaway),</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a> <span class="at">select =</span> <span class="fu">c</span>(osm_id, name, amenity, cuisine,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  takeaway, geometry)) <span class="ot">-&gt;</span> gd_takeaways</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>gd_takeaways</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 160 features and 5 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 18.45562 ymin: 54.30241 xmax: 18.71603 ymax: 54.44475
Geodetic CRS:  WGS 84
First 10 features:
               osm_id                    name    amenity           cuisine
473433244   473433244              McDonald's  fast_food            burger
473433245   473433245                     KFC  fast_food           chicken
478756186   478756186              McDonald's  fast_food            burger
746496055   746496055                   Costa       cafe       coffee_shop
747182709   747182709                     KFC  fast_food           chicken
1538112296 1538112296 Ping Pong ramen &amp; sushi restaurant asian;ramen;sushi
1693970318 1693970318                     KFC  fast_food           chicken
1763555507 1763555507          Zielona Papuga restaurant          regional
1777255606 1777255606          Piwnica Rajców restaurant              &lt;NA&gt;
1783311488 1783311488             Kreska Mąki  fast_food             pizza
           takeaway                  geometry
473433244       yes  POINT (18.6005 54.38275)
473433245       yes  POINT (18.60085 54.3827)
478756186       yes POINT (18.58742 54.35775)
746496055       yes  POINT (18.6487 54.34943)
747182709       yes  POINT (18.6452 54.35604)
1538112296      yes  POINT (18.5671 54.41832)
1693970318      yes POINT (18.57906 54.35757)
1763555507       no  POINT (18.6172 54.37657)
1777255606       no POINT (18.65326 54.34866)
1783311488      yes  POINT (18.58812 54.3596)</code></pre>
</div>
</div>
</section>
<section id="sec-sd-crs" class="level2" data-number="2.2">
<h2 data-number="2.2" data-anchor-id="sec-sd-crs"><span class="header-section-number">2.2</span> Coordinate reference systems</h2>
<p>Since 2019, the representation of coordinate reference systems (CRS) have stabilised in the well-known text format known as WKT2-2019, which is an international standard. The representation supports both two and three dimensional structures, and as implemented in open geospatial software (PROJ) uses definitions stored in a regularly updated database bundled with the software. The database also contains tables defining transformations between CRS, now often based on open access transformation grid files downloaded on-the-fly if required. In parts of the world subject to rapid tectonic movement (the old city centre of Talca, Chile was badly damaged by an earthquake in 2010), CRS change frequently if more by centimetres than by metres.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(talca_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:4674 
  wkt:
GEOGCRS["SIRGAS 2000",
    DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["unknown"],
        AREA["Latin America - SIRGAS 2000 by country"],
        BBOX[-59.87,-122.19,32.72,-25.28]],
    ID["EPSG",4674]]</code></pre>
</div>
</div>
<p>The definition used for stored objects in the <code>chilemapas</code> package is the geographical CRS in decimal degrees called <code>"SIRGAS 2000"</code> based on the <code>"GRS 1980"</code> ellipsoid - geodetic reference system of 1980. The provided data have as is often the case swapped axes compared to the CRS definition. Most geographical information systems keep to <span class="math inline">x</span>, <span class="math inline">y</span>, that is easting, northing or longitude, latitude axis order. Before version 1.0, <code>elevatr</code> reverts to the legacy PROJ4 string representation seen in the summaries above.</p>
<p><code>osmdata</code> and OpenStreetMap appear to assume that all modern geographical coordinate reference systems use <code>"EPSG:4326"</code> as is said to apply to consumer global positioning systems (GPS) devices. This is somewhat accurate, but there is no fixed definition. The definition is usually updated locally for each major tectonic plate, so the WKT2-2019 representation of the CRS used here is as a datum ensemble, with at best two metre accuracy, often worse, as we are noe fourty years on from where the tectonic plates were when <code>"WGS 84</code> was agreed in 1984. Some surveyors have argued that all coordinate tuples should be timestamped, in order to permit the tracking of the movement of points across the earth’s surface and their vertical change as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(talca_takeaways)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCRS["WGS 84",
    ENSEMBLE["World Geodetic System 1984 ensemble",
        MEMBER["World Geodetic System 1984 (Transit)"],
        MEMBER["World Geodetic System 1984 (G730)"],
        MEMBER["World Geodetic System 1984 (G873)"],
        MEMBER["World Geodetic System 1984 (G1150)"],
        MEMBER["World Geodetic System 1984 (G1674)"],
        MEMBER["World Geodetic System 1984 (G1762)"],
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ENSEMBLEACCURACY[2.0]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<p>So while the <code>"SIRGAS 2000"</code> object and the <code>"WGS 84</code> refer approximately to the same representation, some <code>sf</code> predicates and operations on geometries may see them as differing, as for example checking that the Talca take-aways found in the bounding box do lie within the municipality boundaries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">try</span>(<span class="fu">st_within</span>(talca_takeaways, talca_sf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Error in st_geos_binop("within", x, y, sparse = sparse, prepared = prepared,  : 
  st_crs(x) == st_crs(y) is not TRUE</code></pre>
</div>
</div>
<p>Since we know that both are based on the<code>"GRS 1980"</code> ellipsoid, we can overwrite the CRS of the OpenStreetMap take-away outlets location output to bring it into agreement with <code>"SIRGAS 2000"</code>, resulting in finding that all the outlets all lie within the municipality boundaries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>talca_sf <span class="sc">|&gt;</span> <span class="fu">st_crs</span>() <span class="ot">-&gt;</span> sirgas2000</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>talca_takeaways <span class="sc">|&gt;</span> <span class="fu">st_set_crs</span>(sirgas2000) <span class="sc">|&gt;</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">st_within</span>(talca_sf) <span class="sc">|&gt;</span> <span class="fu">unlist</span>() <span class="sc">|&gt;</span> <span class="fu">as.logical</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: st_crs&lt;- : replacing crs does not reproject data; use st_transform for
that</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE</code></pre>
</div>
</div>
<p><span class="citation" data-cites="alvescostaetal:23">Alves Costa et al. (<a href="references.html#ref-alvescostaetal:23" role="doc-biblioref">2023</a>)</span> document current status for the development of SIRGAS, and helpfully show how an increase in ground GPS/GNSS (Global Navigation Satellite Systems from all providers) station density helps track terrestrial movement, which in parts of Chile exceeds 20mm per year. While the movement of the earth’s crust is one source of inaccuracy, another is measurement error, and yet another computational error from repeated use of trigonometrical functions and approximated transformation coefficients. A lack of clarity in defining CRS can lead to the wrong assignation of for example points to polygons.</p>
<p>The Universal Transverse Mercator projection (zone 19 south) is often used for central Chile, and this specific version uses the same <code>"SIRGAS 2000"</code> datum as the input data objects from <code>chilemapas</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(<span class="st">"EPSG:31979"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:31979 
  wkt:
PROJCRS["SIRGAS 2000 / UTM zone 19S",
    BASEGEOGCRS["SIRGAS 2000",
        DATUM["Sistema de Referencia Geocentrico para las AmericaS 2000",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4674]],
    CONVERSION["UTM zone 19S",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-69,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",10000000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Brazil - between 72°W and 66°W, northern and southern hemispheres. In remainder of South America - between 72°W and 66°W, southern hemisphere, onshore and offshore."],
        BBOX[-59.87,-72,2.15,-66]],
    ID["EPSG",31979]]</code></pre>
</div>
</div>
<p>If we check to see which candidate coordinate operations are available, we see that in fact projection accuracy is as good as possible, because the datum definitions of the two CRS are the same:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sf_proj_network</span>(<span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "https://cdn.proj.org"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sf_proj_pipelines</span>(<span class="st">"EPSG:4674"</span>, <span class="st">"EPSG:31979"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Candidate coordinate operations found:  1 
Strict containment:     FALSE 
Axis order auth compl:  FALSE 
Source:  EPSG:4674 
Target:  EPSG:31979 
Best instantiable operation has accuracy: 0 m
Description: axis order change (2D) + UTM zone 19S 
Definition:  +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad
             +step +proj=utm +zone=19 +south +ellps=GRS80</code></pre>
</div>
</div>
<p>If we replace the target CRS with <code>"SIRGAS-Chile 2021 UTM 19S"</code>, <code>sf_proj_pipelines</code> still only finds one candidate, but because no datum transformation from <code>"SIRGAS 2000"</code> to <code>"SIRGAS-Chile 2021"</code> is found in the database, we must accept unknown ballpark accuracy:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sf_proj_pipelines</span>(<span class="st">"EPSG:4674"</span>, <span class="st">"EPSG:20049"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Candidate coordinate operations found:  1 
Strict containment:     FALSE 
Axis order auth compl:  FALSE 
Source:  EPSG:4674 
Target:  EPSG:20049 
Best instantiable operation has only ballpark accuracy 
Description: axis order change (2D) + Ballpark geographic offset from SIRGAS
             2000 to SIRGAS-Chile 2021 + UTM zone 19S
Definition:  +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad
             +step +proj=utm +zone=19 +south +ellps=GRS80</code></pre>
</div>
</div>
<p>Many national and international mapping agencies have provided open access transformation grids that PROJ can use on-the-fly (https://cdn.proj.org/), but neither Chile not SIRGAS have contributed any such grid so far. Grids are more accurate than three or seven parameter transformations because they allow local crustal deformations to be applied, rather than averaged over the whole area of application. Accuracy is now much more important as GPS/GNSS has become established in navigation, precision farming, construction, etc.</p>
<p>Let us repeat the measurement of the area of Región del Maule after projection to <code>"UTM 19S"</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>maule_sf <span class="sc">|&gt;</span> <span class="fu">st_union</span>() <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="st">"EPSG:31979"</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">st_area</span>() <span class="sc">|&gt;</span> units<span class="sc">::</span><span class="fu">set_units</span>(<span class="st">"km2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>30314.34 [km^2]</code></pre>
</div>
</div>
<p>The area is now more than 16 square kilometres greater than the area from Wikipedia, and the area calculated by <code>s2</code> on the surface of the earth. All projections distort the rounded surface of the earth by squeezing the centre of the area of interest and stretching the edges to force it into planar form, so depending on the statutory regulations, all measured areas are approximate in one way or another.</p>
<p>Let us now move to the CRS of the boundary of the county of Gdańsk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(gd_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:2180 
  wkt:
PROJCRS["ETRF2000-PL / CS92",
    BASEGEOGCRS["ETRF2000-PL",
        DATUM["ETRF2000 Poland",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",9702]],
    CONVERSION["Poland CS92",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",19,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9993,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-5300000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (x)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (y)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Topographic mapping (medium and small scale)."],
        AREA["Poland - onshore and offshore."],
        BBOX[49,14.14,55.93,24.15]],
    ID["EPSG",2180]]</code></pre>
</div>
</div>
<p>Poland currently uses the European Terrestrial Reference Frame (ETRF) and lies on a tectonic plate with little deformation activity, although the plate itself is moving up to 20mm a year. The projection <code>"ETRF2000-PL / CS92"</code> was adopted following the dissolution of the Warsaw Pact - mapping everywhere is driven at base by the needs of military operations.</p>
<p>The CRS of the take-away outlets is as for Talca:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(gd_takeaways)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCRS["WGS 84",
    ENSEMBLE["World Geodetic System 1984 ensemble",
        MEMBER["World Geodetic System 1984 (Transit)"],
        MEMBER["World Geodetic System 1984 (G730)"],
        MEMBER["World Geodetic System 1984 (G873)"],
        MEMBER["World Geodetic System 1984 (G1150)"],
        MEMBER["World Geodetic System 1984 (G1674)"],
        MEMBER["World Geodetic System 1984 (G1762)"],
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ENSEMBLEACCURACY[2.0]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<p>and the transformation pipeline from <code>"ETRF2000-PL / CS92"</code> to <code>"WGS 84"</code> has an accuracy of 1 metre:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sf_proj_pipelines</span>(<span class="st">"EPSG:2180"</span>, <span class="st">"EPSG:4326"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Candidate coordinate operations found:  2 
Strict containment:     FALSE 
Axis order auth compl:  FALSE 
Source:  EPSG:2180 
Target:  EPSG:4326 
Best instantiable operation has accuracy: 1 m
Description: axis order change (2D) + Inverse of Poland CS92 + ETRF2000-PL
             to WGS 84 (1) + axis order change (2D)
Definition:  +proj=pipeline +step +inv +proj=tmerc +lat_0=0 +lon_0=19
             +k=0.9993 +x_0=500000 +y_0=-5300000 +ellps=GRS80
             +step +proj=unitconvert +xy_in=rad +xy_out=deg</code></pre>
</div>
</div>
<p>Since none of these projections/transformations have required datum transformation, let us use the example of <code>"OSGB36 / British National Grid"</code> to <code>"WGS 84"</code>. We can see that the <code>"Ordnance Survey of Great Britain 1936"</code> datum uses a different ellipsoid: <code>"Airy 1830"</code> from <code>"GRS 1980"</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(<span class="st">"EPSG:27700"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:27700 
  wkt:
PROJCRS["OSGB36 / British National Grid",
    BASEGEOGCRS["OSGB36",
        DATUM["Ordnance Survey of Great Britain 1936",
            ELLIPSOID["Airy 1830",6377563.396,299.3249646,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4277]],
    CONVERSION["British National Grid",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",49,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-2,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996012717,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",400000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-100000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore."],
        BBOX[49.75,-9.01,61.01,2.01]],
    ID["EPSG",27700]]</code></pre>
</div>
</div>
<p>If we then query the database to find the most accurate transformation with enabled access to transformation grids, we can achieve 1 metre:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sf_proj_pipelines</span>(<span class="st">"EPSG:27700"</span>, <span class="st">"EPSG:4326"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Candidate coordinate operations found:  9 
Strict containment:     FALSE 
Axis order auth compl:  FALSE 
Source:  EPSG:27700 
Target:  EPSG:4326 
Best instantiable operation has accuracy: 1 m
Description: Inverse of British National Grid + OSGB36 to WGS 84 (9) + axis
             order change (2D)
Definition:  +proj=pipeline +step +inv +proj=tmerc +lat_0=49 +lon_0=-2
             +k=0.9996012717 +x_0=400000 +y_0=-100000
             +ellps=airy +step +proj=hgridshift
             +grids=uk_os_OSTN15_NTv2_OSGBtoETRS.tif +step
             +proj=unitconvert +xy_in=rad +xy_out=deg</code></pre>
</div>
</div>
<p>The parts of the grid file <code>uk_os_OSTN15_NTv2_OSGBtoETRS.tif</code> needed for the data in question can be downloaded automatically on-the-fly if PROJ network access is enabled, and cached locally for any software using PROJ for handling CRS; the grid file offsets are shown in Figure 2.4, page 25 of <span class="citation" data-cites="pebesma+bivand:23">Pebesma and Bivand (<a href="references.html#ref-pebesma+bivand:23" role="doc-biblioref">2023</a>)</span>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-alvescostaetal:23" class="csl-entry" role="listitem">
Alves Costa, Sonia M., Laura Sánchez, Diego Piñón, José A. Tarrio Mosquera, Gabriel Guimarães, Demián D. Gómez, Hermann Drewes, et al. 2023. <span>“Status of the SIRGAS Reference Frame: Recent Developments and New Challenges.”</span> In <em>International Association of Geodesy Symposia</em>, 1–13. Berlin, Heidelberg: Springer Berlin Heidelberg. <a href="https://doi.org/10.1007/1345_2023_227">https://doi.org/10.1007/1345_2023_227</a>.
</div>
<div id="ref-bivand:22" class="csl-entry" role="listitem">
Bivand, Roger. 2022. <span>“Analytical Environments.”</span> In <em>Handbook of Spatial Analysis in the Social Sciences</em>, edited by Sergio J. Rey and Rachel Franklin, 36–63. Camberley, UK: Edward Elgar. <a href="https://hdl.handle.net/11250/3065981">https://hdl.handle.net/11250/3065981</a>.
</div>
<div id="ref-dyba+nowosad:21" class="csl-entry" role="listitem">
Dyba, Krzysztof, and Jakub Nowosad. 2021. <span>“Rgugik: Search and Retrieve Spatial Data from the Polish Head Office of Geodesy and Cartography in r.”</span> <em>Journal of Open Source Software</em> 6 (59): 2948. <a href="https://doi.org/10.21105/joss.02948">https://doi.org/10.21105/joss.02948</a>.
</div>
<div id="ref-lovelaceetal:19" class="csl-entry" role="listitem">
Lovelace, Robin, Jakub Nowosad, and Jannes Muenchow. 2019. <em>Geocomputation with <span>R</span></em>. CRC Press.<a href=" https://r.geocompx.org/ ">https://r.geocompx.org/ </a>.
</div>
<div id="ref-padghametal:17" class="csl-entry" role="listitem">
Mark Padgham, Bob Rudis, Robin Lovelace, and Maëlle Salmon. 2017. <span>“Osmdata.”</span> <em>Journal of Open Source Software</em> 2 (14): 305. <a href="https://doi.org/10.21105/joss.00305">https://doi.org/10.21105/joss.00305</a>.
</div>
<div id="ref-pebesma+bivand:23" class="csl-entry" role="listitem">
Pebesma, Edzer, and Roger Bivand. 2023. <em>Spatial Data Science with Applications in <span>R</span></em>. Boca Raton, FL: CRC Press.
</div>
<div id="ref-reyetal:23" class="csl-entry" role="listitem">
Rey, Sergio, Dani Arribas-Bel, and Levi John Wolf. 2023. <em>Geographic Data Science with <span>Python</span></em>. Boca Raton, FL: CRC Press. <a href="https://geographicdata.science">https://geographicdata.science</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01_talk.html" class="pagination-link" aria-label="Introducing Spatial Econometrics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducing Spatial Econometrics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03_talk.html" class="pagination-link" aria-label="Working with spatial data">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Working with spatial data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>